// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sinch.Config.Mgmt.Persistence;

#nullable disable

namespace Sinch.Config.Mgmt.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20220913122605_Created Database Tables")]
    partial class CreatedDatabaseTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Sinch.Config.Mgmt.Persistence.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Sinch.Config.Mgmt.Persistence.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<Guid>("EnviromentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnviromentId");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Sinch.Config.Mgmt.Persistence.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("Sinch.Config.Mgmt.Persistence.Configuration", b =>
                {
                    b.HasOne("Sinch.Config.Mgmt.Persistence.Environment", "Enviroment")
                        .WithMany()
                        .HasForeignKey("EnviromentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enviroment");
                });

            modelBuilder.Entity("Sinch.Config.Mgmt.Persistence.Environment", b =>
                {
                    b.HasOne("Sinch.Config.Mgmt.Persistence.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });
#pragma warning restore 612, 618
        }
    }
}
