// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sinch.Config.Mgmt.Persistence;

#nullable disable

namespace Sinch.Config.Mgmt.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    partial class ConfigDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Sinch.Config.Mgmt.Persistence.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ab55dd4-eb05-4355-b657-219fd3f50667"),
                            Description = "RTC API Gateway",
                            Name = "RTC.ApiGateway"
                        },
                        new
                        {
                            Id = new Guid("a75017e9-70f7-4363-8d73-1b8f306c2008"),
                            Description = "RTC Calling API",
                            Name = "RTC.CallingApi"
                        },
                        new
                        {
                            Id = new Guid("4ec370a1-1ccf-489b-bf39-c3580356f407"),
                            Description = "RTC Calling Application",
                            Name = "RTC.CallingApplication"
                        },
                        new
                        {
                            Id = new Guid("3e8e1230-f26e-4cd0-aecc-5d64637f9278"),
                            Description = "RTC Calling Service",
                            Name = "RTC.CallingService"
                        },
                        new
                        {
                            Id = new Guid("626090f5-296d-4b8b-8a89-2557f773755b"),
                            Description = "RTC Billing Application",
                            Name = "RTC.BillingApplication"
                        },
                        new
                        {
                            Id = new Guid("a70247a8-4d49-43b3-94be-1ef6455734cb"),
                            Description = "RTC Billing Service",
                            Name = "RTC.BillingService"
                        });
                });

            modelBuilder.Entity("Sinch.Config.Mgmt.Persistence.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<Guid>("EnviromentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnviromentId");

                    b.ToTable("Configurations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("852712a9-9478-4e13-9e37-159ce2bdbf04"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("0985a1fc-b891-490a-9937-f6881d0cbc30")
                        },
                        new
                        {
                            Id = new Guid("a805da67-1b3c-409c-82a2-01be1376c403"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("1a884483-a7a8-4c45-b617-75ecfa62deb8")
                        },
                        new
                        {
                            Id = new Guid("794cb141-a1a3-4ced-8e79-292e285a9b54"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("267a7710-7a87-4c3d-926f-910776adfda7")
                        },
                        new
                        {
                            Id = new Guid("cdfa52b6-7bc7-430f-9d09-7c5566705801"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("360cb85a-1d94-4de0-8cae-d5759f820490")
                        },
                        new
                        {
                            Id = new Guid("78dc480e-14f4-424e-825b-c8cb5a3b8df9"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("3c1cc7ed-944f-44ac-a05b-a63f8402f106")
                        },
                        new
                        {
                            Id = new Guid("6452ed7a-195a-4b9c-8395-aab6e24e6775"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("3773fe57-a236-49a5-9ad6-94f0189140e0")
                        },
                        new
                        {
                            Id = new Guid("8be9a73e-8d48-45d9-84c7-d0c9018ce260"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("1f9b6afe-5725-4ad0-9460-2abaed19ba36")
                        },
                        new
                        {
                            Id = new Guid("0b80ceea-a545-4e65-a7a4-f4a470092b35"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("27c43d20-1289-4aed-8a6d-2573b8131a55")
                        },
                        new
                        {
                            Id = new Guid("20040139-5c21-4175-b0f8-a4b37b045a37"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("0a75bc9e-470e-4468-a2f8-3a9dda933306")
                        },
                        new
                        {
                            Id = new Guid("c2d6773e-c8c6-4f86-b26c-25b270df82a2"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("3acbb91d-6c21-43f2-b246-0cadd1ad3063")
                        },
                        new
                        {
                            Id = new Guid("2449c283-b607-4029-8165-45779461ad72"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("75d92b56-aa0f-4fad-a289-4978129baef5")
                        },
                        new
                        {
                            Id = new Guid("0a045b8a-5551-4366-acf6-aad1bdfdef57"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("c6014659-421e-4e7a-a0a2-85cfdadbfce9")
                        },
                        new
                        {
                            Id = new Guid("0ba6815e-3a32-4596-a998-e142ef7a1a15"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("a4ae0560-1803-4a21-8e05-dfdd3a7d6a11")
                        },
                        new
                        {
                            Id = new Guid("a1ef1a77-3ada-4206-854f-7b8365aae79a"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("6b4faf7a-b500-4a24-91e1-e187e2b356a0")
                        },
                        new
                        {
                            Id = new Guid("8951a51f-ca42-4226-afaa-378e6ab8c681"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("94e02d01-f5f3-40b8-b249-9418f9bb716e")
                        },
                        new
                        {
                            Id = new Guid("60668921-ba9d-4f1f-bd04-b2646e7679da"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("6a35823e-1c19-48d1-9afa-a484763369ce")
                        },
                        new
                        {
                            Id = new Guid("9d20c762-f2a5-40d1-9b16-574779728d29"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("f3edd593-2816-4cda-9eb6-63f1a17f378e")
                        },
                        new
                        {
                            Id = new Guid("7c84dddc-530b-4489-93ad-5cc6299b0749"),
                            Active = true,
                            Data = "{\"AllowedHosts\":\"*\",\"ConnectionStrings\":{\"Sqlite\":\"Data Source=.\\\\app.db\"},\"Logging\":{\"LogLevel\":{\"Default\":\"Warning\",\"Microsoft.AspNetCore\":\"Warning\",\"Sinch\":\"Information\"}}}",
                            EnviromentId = new Guid("7ba2b7b2-eb4a-4193-b1f4-0f786a31bd03")
                        });
                });

            modelBuilder.Entity("Sinch.Config.Mgmt.Persistence.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Environments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0985a1fc-b891-490a-9937-f6881d0cbc30"),
                            ApplicationId = new Guid("3ab55dd4-eb05-4355-b657-219fd3f50667"),
                            Name = "Dev",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("1a884483-a7a8-4c45-b617-75ecfa62deb8"),
                            ApplicationId = new Guid("3ab55dd4-eb05-4355-b657-219fd3f50667"),
                            Name = "Qa",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("267a7710-7a87-4c3d-926f-910776adfda7"),
                            ApplicationId = new Guid("3ab55dd4-eb05-4355-b657-219fd3f50667"),
                            Name = "Prod",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("360cb85a-1d94-4de0-8cae-d5759f820490"),
                            ApplicationId = new Guid("a75017e9-70f7-4363-8d73-1b8f306c2008"),
                            Name = "Dev",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("3c1cc7ed-944f-44ac-a05b-a63f8402f106"),
                            ApplicationId = new Guid("a75017e9-70f7-4363-8d73-1b8f306c2008"),
                            Name = "Qa",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("3773fe57-a236-49a5-9ad6-94f0189140e0"),
                            ApplicationId = new Guid("a75017e9-70f7-4363-8d73-1b8f306c2008"),
                            Name = "Prod",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("1f9b6afe-5725-4ad0-9460-2abaed19ba36"),
                            ApplicationId = new Guid("4ec370a1-1ccf-489b-bf39-c3580356f407"),
                            Name = "Dev",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("27c43d20-1289-4aed-8a6d-2573b8131a55"),
                            ApplicationId = new Guid("4ec370a1-1ccf-489b-bf39-c3580356f407"),
                            Name = "Qa",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("0a75bc9e-470e-4468-a2f8-3a9dda933306"),
                            ApplicationId = new Guid("4ec370a1-1ccf-489b-bf39-c3580356f407"),
                            Name = "Prod",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("3acbb91d-6c21-43f2-b246-0cadd1ad3063"),
                            ApplicationId = new Guid("3e8e1230-f26e-4cd0-aecc-5d64637f9278"),
                            Name = "Dev",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("75d92b56-aa0f-4fad-a289-4978129baef5"),
                            ApplicationId = new Guid("3e8e1230-f26e-4cd0-aecc-5d64637f9278"),
                            Name = "Qa",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("c6014659-421e-4e7a-a0a2-85cfdadbfce9"),
                            ApplicationId = new Guid("3e8e1230-f26e-4cd0-aecc-5d64637f9278"),
                            Name = "Prod",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("a4ae0560-1803-4a21-8e05-dfdd3a7d6a11"),
                            ApplicationId = new Guid("626090f5-296d-4b8b-8a89-2557f773755b"),
                            Name = "Dev",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("6b4faf7a-b500-4a24-91e1-e187e2b356a0"),
                            ApplicationId = new Guid("626090f5-296d-4b8b-8a89-2557f773755b"),
                            Name = "Qa",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("94e02d01-f5f3-40b8-b249-9418f9bb716e"),
                            ApplicationId = new Guid("626090f5-296d-4b8b-8a89-2557f773755b"),
                            Name = "Prod",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("6a35823e-1c19-48d1-9afa-a484763369ce"),
                            ApplicationId = new Guid("a70247a8-4d49-43b3-94be-1ef6455734cb"),
                            Name = "Dev",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("f3edd593-2816-4cda-9eb6-63f1a17f378e"),
                            ApplicationId = new Guid("a70247a8-4d49-43b3-94be-1ef6455734cb"),
                            Name = "Qa",
                            Region = "EU-West1"
                        },
                        new
                        {
                            Id = new Guid("7ba2b7b2-eb4a-4193-b1f4-0f786a31bd03"),
                            ApplicationId = new Guid("a70247a8-4d49-43b3-94be-1ef6455734cb"),
                            Name = "Prod",
                            Region = "EU-West1"
                        });
                });

            modelBuilder.Entity("Sinch.Config.Mgmt.Persistence.Configuration", b =>
                {
                    b.HasOne("Sinch.Config.Mgmt.Persistence.Environment", "Enviroment")
                        .WithMany()
                        .HasForeignKey("EnviromentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enviroment");
                });

            modelBuilder.Entity("Sinch.Config.Mgmt.Persistence.Environment", b =>
                {
                    b.HasOne("Sinch.Config.Mgmt.Persistence.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });
#pragma warning restore 612, 618
        }
    }
}
